export const site = {
  name: "Strange But True: The Desire Atlas",
  shortName: "The Desire Atlas",
  url: "https://auraofintelligence.github.io/strange-but-true-desire-atlas/",
  repoUrl: "https://github.com/auraofintelligence/strange-but-true-desire-atlas",
  contactUrl: "https://auraofintelligence.github.io/strange-but-true/contact.html",
  checkedAt: "15 August 2026",
  assetVersion: "20260815c"
};

export const pages = [
  {
    file: "index.html",
    nav: "Home",
    group: "Explore",
    title: "Love stories for the edge of tomorrow",
    description: "A global atlas of readers, gatherings, markets and lawful routes for speculative love stories.",
    eyebrow: "A Strange But True field guide",
    heading: "Love stories for the edge of tomorrow.",
    lead: "Find the readers, gatherings, markets and lawful routes for near-future romance, science-fiction romance and romantasy, while keeping facts, hopes and wild possibilities honest.",
    image: "hero-home.webp",
    imageAlt: "Adult writers and explorers around an open circular table above a luminous night-time Earth, with a heart-shaped constellation overhead.",
    align: "left",
    imagePosition: "center"
  },
  {
    file: "readers.html",
    nav: "Reader Atlas",
    group: "Explore",
    title: "Reader Atlas",
    description: "Scoped reader evidence and a transparent audience-hypothesis builder.",
    eyebrow: "Explore / Reader Atlas",
    heading: "Meet the audience without inventing them.",
    lead: "Compare what limited surveys actually measured, then build a testable reader hypothesis without turning an old sample into a global truth.",
    image: "hero-market.webp",
    imageAlt: "A glowing globe connected to books, reading devices, headphones and small reader circles in a vast midnight library.",
    align: "left",
    imagePosition: "center"
  },
  {
    file: "tribe.html",
    nav: "Tribe Directory",
    group: "Explore",
    title: "Tribe Directory",
    description: "Reader, writer and professional communities for speculative romance explorers.",
    eyebrow: "Explore / Tribe Directory",
    heading: "Arrive as a participant, not a funnel.",
    lead: "Find moderated reader circles, writer organisations and speculative-fiction communities. Read the room, follow the rules and contribute before promoting.",
    image: "hero-tribe.webp",
    imageAlt: "A diverse group of adult readers and writers meeting at a near-future coastal book festival beneath an aurora and heart constellation.",
    align: "right",
    imagePosition: "center"
  },
  {
    file: "gatherings.html",
    nav: "Gatherings",
    group: "Explore",
    title: "Global Gatherings",
    description: "A dated watchlist of romance, publishing and speculative-fiction events.",
    eyebrow: "Explore / Gatherings",
    heading: "Put real rooms on the map.",
    lead: "A source-linked watchlist for conferences, rights meetings, reader events and speculative-fiction gatherings around the world.",
    image: "hero-tribe.webp",
    imageAlt: "Adult readers, writers and publishers in conversation at a luminous international book festival beside the ocean.",
    align: "right",
    imagePosition: "center"
  },
  {
    file: "market.html",
    nav: "Market Signals",
    group: "Publish",
    title: "Market Signals",
    description: "Time-stamped romance, fiction and audiobook market signals with clear scope limits.",
    eyebrow: "Publish / Market Signals",
    heading: "Big signals. Small print. No crystal ball.",
    lead: "Romance, fantasy and audio are moving, but every number belongs to a year, territory, format and method. This page keeps the labels attached.",
    image: "hero-market.webp",
    imageAlt: "A luminous global story ecosystem linking physical books, digital reading, audio and community tables.",
    align: "left",
    imagePosition: "center"
  },
  {
    file: "channels.html",
    nav: "Sales & Channels",
    group: "Publish",
    title: "Sales and Channels",
    description: "A planning calculator and official-source publishing-channel comparison.",
    eyebrow: "Publish / Sales & Channels",
    heading: "Turn a dream into numbers you can challenge.",
    lead: "Model a sales target, compare exclusive and wide routes, and keep author revenue, gross price, platform rules and actual demand separate.",
    image: "hero-market.webp",
    imageAlt: "Books, listening devices and warm reader spaces orbiting a luminous world in a midnight library.",
    align: "left",
    imagePosition: "center"
  },
  {
    file: "countries.html",
    nav: "Country Editions",
    group: "Publish",
    title: "Country Editions",
    description: "A cautious country-edition matrix for law, classification, access and platform review.",
    eyebrow: "Publish / Country Editions",
    heading: "A map of questions, not legal clearance.",
    lead: "National law, customs, classification, age access and retailer policy can all apply separately. Every route here still needs a human check.",
    image: "hero-boundaries.webp",
    imageAlt: "Three adult writers pause at a transparent observatory where illuminated paths divide towards different horizons.",
    align: "right",
    imagePosition: "center"
  },
  {
    file: "storyworld.html",
    nav: "Storyworld Shelf",
    group: "Imagine",
    title: "Storyworld Shelf",
    description: "Consent-centred prompts for AI futures, chosen family and plural relationship fiction.",
    eyebrow: "Imagine / Storyworld Shelf",
    heading: "Many futures. Nobody becomes property.",
    lead: "Explore chosen family, plural households, emerging AI and joyful responsible abundance as story questions, with autonomy and genuine exits designed in.",
    image: "hero-storyworld.webp",
    imageAlt: "A diverse group of adults sharing a generous table in a biophilic future home with private rooms, an open doorway and one empty chair.",
    align: "left",
    imagePosition: "center"
  },
  {
    file: "consent.html",
    nav: "Consent Compass",
    group: "Imagine",
    title: "Consent and Content Compass",
    description: "Editorial boundaries for adult agency, explicit consent, power, privacy and exit.",
    eyebrow: "Imagine / Consent Compass",
    heading: "The edge only works when everyone can step back.",
    lead: "Consent is informed, freely given, specific, ongoing and reversible. AI, chemistry, popularity and group pressure do not get to replace a human yes.",
    image: "hero-boundaries.webp",
    imageAlt: "Adult writers with books and compass lights pause together before choosing between illuminated pathways.",
    align: "right",
    imagePosition: "center"
  },
  {
    file: "ledger.html",
    nav: "Reality Ledger",
    group: "Imagine",
    title: "Reality Ledger",
    description: "A visible ledger separating evidence, proposals, fiction, wild cards and review gates.",
    eyebrow: "Imagine / Reality Ledger",
    heading: "Blend the worldview. Keep the labels.",
    lead: "The Atlas deliberately lets personal philosophy, current evidence and fiction share a table. The ledger stops them borrowing one another's authority.",
    image: "hero-home.webp",
    imageAlt: "Adult explorers around an open table, with books and a luminous world map below a heart-shaped constellation.",
    align: "left",
    imagePosition: "center"
  },
  {
    file: "sources.html",
    nav: "Sources & Method",
    group: "Trust",
    title: "Sources and Method",
    description: "The source register, evidence labels, update method and unresolved research gaps.",
    eyebrow: "Trust / Sources & Method",
    heading: "Show the receipts and the missing pieces.",
    lead: "Every consequential claim should lead back to a source, a scope and a date. Where comparable evidence is missing, the gap remains visible.",
    image: "hero-boundaries.webp",
    imageAlt: "A transparent observatory opens onto several illuminated paths under a night sky.",
    align: "right",
    imagePosition: "center"
  },
  {
    file: "licence.html",
    nav: "Licence & Contact",
    group: "Trust",
    title: "Licence and Contact",
    description: "The custom Strange But True public source licence, contact route and project boundaries.",
    eyebrow: "Trust / Licence & Contact",
    heading: "Public to explore. Permission still has boundaries.",
    lead: "Read, learn, discuss and adapt for allowed non-commercial uses with credit. Commercial, corporate, institutional, government, startup, agency, client and employer uses need written permission from Luke Nathan Hayes.",
    image: "hero-home.webp",
    imageAlt: "A shared table overlooking a luminous world, with one open chair and a heart constellation in the night sky.",
    align: "left",
    imagePosition: "center"
  }
];

export const groups = ["Explore", "Publish", "Imagine", "Trust"];
