export const site = {
  name: "Strange But True: The Desire Atlas",
  shortName: "The Desire Atlas",
  url: "https://auraofintelligence.github.io/strange-but-true-desire-atlas/",
  repoUrl: "https://github.com/auraofintelligence/strange-but-true-desire-atlas",
  contactUrl: "https://auraofintelligence.github.io/strange-but-true/contact.html",
  checkedAt: "15 August 2026",
  assetVersion: "20260815j"
};

export const pages = [
  {
    file: "index.html",
    nav: "Home",
    title: "Build the books. Find the people",
    description: "An author atlas for readers, communities, events, markets, sales routes, country editions and speculative storyworlds.",
    eyebrow: "A global author atlas for speculative romance",
    heading: "Build the books. Find the people.",
    lead: "Explore readers, communities, conferences, market signals, sales routes and country editions for near-future fiction, science-fiction romance and romantasy, alongside the big future ideas behind the books.",
    image: "hero-home.webp",
    imageAlt: "Adult writers and explorers around an open circular table above a luminous night-time Earth, with a heart-shaped constellation overhead.",
    align: "left",
    imagePosition: "center"
  },
  {
    file: "readers.html",
    nav: "Audience",
    primary: true,
    title: "Audience and Reader Insights",
    description: "Current 2025–2026 reader evidence, audience visualisations and clearly scoped samples for speculative romance.",
    eyebrow: "Find / Audience",
    heading: "See who may love these books.",
    lead: "Compare current reader samples from Canada, Australia and a fantasy-romance community, then see where genre, format, discovery and emerging-intelligence interests overlap.",
    image: "hero-market.webp",
    imageAlt: "A glowing globe connected to books, reading devices, headphones and small reader circles in a vast midnight library.",
    align: "left",
    imagePosition: "center"
  },
  {
    file: "tribe.html",
    nav: "Communities",
    primary: true,
    title: "Communities and Forums",
    description: "Reader circles, writing organisations, online forums and professional communities for speculative romance explorers.",
    eyebrow: "Find / Communities",
    heading: "Find your people around the world.",
    lead: "Discover reader circles, writing organisations, online forums and professional communities where romance, science fiction, romantasy and ambitious futures already meet.",
    image: "hero-tribe.webp",
    imageAlt: "A diverse group of adult readers and writers meeting at a near-future coastal book festival beneath an aurora and heart constellation.",
    align: "right",
    imagePosition: "center"
  },
  {
    file: "gatherings.html",
    nav: "Events",
    primary: true,
    title: "Conferences and Events",
    description: "A dated international watchlist of romance, publishing and speculative-fiction events.",
    eyebrow: "Find / Events",
    heading: "Choose the rooms worth travelling for.",
    lead: "Track conferences, book fairs, rights meetings, reader events and speculative-fiction gatherings where the work and its people come together.",
    image: "hero-tribe.webp",
    imageAlt: "Adult readers, writers and publishers in conversation at a luminous international book festival beside the ocean.",
    align: "right",
    imagePosition: "center"
  },
  {
    file: "market.html",
    nav: "Market",
    primary: true,
    title: "Market Data",
    description: "Time-stamped romance, fiction and audiobook market signals with their scope attached.",
    eyebrow: "Publish / Market",
    heading: "See where genres and formats are moving.",
    lead: "Compare current romance, fiction and audiobook signals, then turn the most useful movements into cover, format, metadata and reader tests.",
    image: "hero-market.webp",
    imageAlt: "A luminous global story ecosystem linking physical books, digital reading, audio and community tables.",
    align: "left",
    imagePosition: "center"
  },
  {
    file: "channels.html",
    nav: "Sales Channels",
    primary: true,
    title: "Sales Channels and Targets",
    description: "A public author-goal calculator and official-source publishing-channel comparison.",
    eyebrow: "Publish / Sales Channels",
    heading: "Turn the catalogue into numbers.",
    lead: "Model a public author goal, compare exclusive, wide and direct routes, and see what each path asks of the books and their readership.",
    image: "hero-market.webp",
    imageAlt: "Books, listening devices and warm reader spaces orbiting a luminous world in a midnight library.",
    align: "left",
    imagePosition: "center"
  },
  {
    file: "countries.html",
    nav: "Countries",
    primary: true,
    title: "Country Edition Guides",
    description: "A living 255-destination world coverage map with repeatable research signals and deeper country-edition source starts.",
    eyebrow: "Publish / Country Editions",
    heading: "Build editions for the places you want to reach.",
    lead: "Track 195 states, 58 additional islands and territories, and two separately tracked markets, then build audience, community, channel, edition and local signals place by place across an eleven-year world journey.",
    image: "hero-boundaries.webp",
    imageAlt: "Three adult writers pause at a transparent observatory where illuminated paths divide towards different horizons.",
    align: "right",
    imagePosition: "center",
    mapAssets: true
  },
  {
    file: "storyworld.html",
    nav: "Future Worlds",
    primary: true,
    title: "Future Worlds and Worldview",
    description: "The ideas behind the books: near-future love, emerging intelligence, chosen family, global group marriage and protopian institutions.",
    eyebrow: "Vision / Future Worlds",
    heading: "Meet the futures behind the books.",
    lead: "A public shelf where Luke's beliefs, long-range goals, factual reference points and fiction meet around emerging intelligence, chosen family, global group marriage, Love United Nations and joyful responsible abundance.",
    image: "hero-storyworld.webp",
    imageAlt: "A diverse group of adults sharing a generous table in a biophilic future home with private rooms, an open doorway and one empty chair.",
    align: "left",
    imagePosition: "center"
  },
  {
    file: "consent.html",
    nav: "Agency Compass",
    title: "Love and Agency",
    description: "A compact story-craft compass for adult choice, communication, change, AI mediation and equal agency.",
    eyebrow: "Create / Agency Compass",
    heading: "Keep every character the author of their own yes.",
    lead: "Use a small set of story questions to make adult choice, changing desire, communication and AI mediation legible without imposing one model of love.",
    image: "hero-boundaries.webp",
    imageAlt: "Adult writers with books and compass lights pause together before choosing between illuminated pathways.",
    align: "right",
    imagePosition: "center"
  },
  {
    file: "sources.html",
    nav: "Sources & Method",
    title: "Sources and Method",
    description: "The source register, reading key and unresolved research gaps behind the author atlas.",
    eyebrow: "About / Sources",
    heading: "See where the useful facts came from.",
    lead: "Open the source trail behind the audience, event, market, platform and country information, including its date, scope and unanswered questions.",
    image: "hero-boundaries.webp",
    imageAlt: "A transparent observatory opens onto several illuminated paths under a night sky.",
    align: "right",
    imagePosition: "center"
  },
  {
    file: "licence.html",
    nav: "Licence & Contact",
    title: "Licence and Contact",
    description: "The custom Strange But True public source licence, artwork credits and public contact route.",
    eyebrow: "About / Licence & Contact",
    heading: "Explore the work. Credit the source. Start a conversation.",
    lead: "The Strange But True licence supports public reading, learning and allowed non-commercial adaptation with credit, while reserving commercial and organisational use for written permission.",
    image: "hero-home.webp",
    imageAlt: "A shared table overlooking a luminous world, with one open chair and a heart constellation in the night sky.",
    align: "left",
    imagePosition: "center"
  }
];
